language: ruby

sudo: false

matrix:
  include:
    - rvm: 2.3.1
      gemfile: Gemfile
      before_script:
        - bundle exec danger
    - rvm: 2.3.1
      gemfile: gemfiles/rails_3.gemfile
    - rvm: 2.3.1
      gemfile: gemfiles/rails_4.gemfile
    - rvm: 2.3.1
      gemfile: gemfiles/rack_1.5.2.gemfile
    - rvm: 2.3.0
    - rvm: 2.2.5
    - rvm: rbx-2
    - rvm: ruby-head
    - rvm: jruby-head
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2

bundler_args: --without development
