name: test

on: [push, pull_request]

jobs:
  lint:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
        bundler-cache: true
        rubygems: latest

    - name: Run RuboCop
      run: bundle exec rubocop

  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.2', '3.3', '3.4', '4.0']
        gemfile:
          - Gemfile
          - gemfiles/rack_2_2.gemfile
          - gemfiles/rack_3_0.gemfile
          - gemfiles/rack_3_1.gemfile
          - gemfiles/rack_3_2.gemfile
          - gemfiles/rails_7_2.gemfile
          - gemfiles/rails_8_0.gemfile
          - gemfiles/rails_8_1.gemfile
        specs: ['spec --exclude-pattern=spec/integration/{grape_entity,hashie,dry_validation,multi_*}/*_spec.rb']
        include:
          - ruby: '4.0'
            gemfile: gemfiles/grape_entity.gemfile
            specs: 'spec/integration/grape_entity'
          - ruby: '4.0'
            gemfile: gemfiles/hashie.gemfile
            specs: 'spec/integration/hashie'
          - ruby: '4.0'
            gemfile: gemfiles/dry_validation.gemfile
            specs: 'spec/integration/dry_validation'
          - ruby: '4.0'
            gemfile: gemfiles/multi_json.gemfile
            specs: 'spec/integration/multi_json'
          - ruby: '4.0'
            gemfile: gemfiles/multi_xml.gemfile
            specs: 'spec/integration/multi_xml'
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run Tests (${{ matrix.specs }})
      run: "RUBYOPT='--enable=frozen-string-literal' bundle exec rspec ${{ matrix.specs }}"

    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        flag-name: run-${{ matrix.ruby }}-${{ matrix.gemfile }}
        parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
