---
name: test
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  lint:
    name: RuboCop
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Run RuboCop
      run: bundle exec rubocop
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.5
          - 2.6
          - 2.7
          - "3.0"
        gemfile:
          - Gemfile
          - gemfiles/rack1.gemfile
          - gemfiles/rack2.gemfile
          - gemfiles/rack2_2.gemfile
          - gemfiles/rails_5.gemfile
          - gemfiles/rails_6.gemfile
          - gemfiles/rails_6_1.gemfile
        include:
          - ruby: 3.1
            gemfile: 'gemfiles/multi_json.gemfile'
          - ruby: 3.1
            gemfile: 'gemfiles/multi_xml.gemfile'
          - ruby: 3.1
            gemfile: 'gemfiles/rails_7.gemfile'
          - ruby: "3.0"
            gemfile: 'gemfiles/multi_json.gemfile'
          - ruby: "3.0"
            gemfile: 'gemfiles/multi_xml.gemfile'
          - ruby: "3.0"
            gemfile: 'gemfiles/rails_7.gemfile'
          - ruby: 2.7
            gemfile: 'gemfiles/multi_json.gemfile'
          - ruby: 2.7
            gemfile: 'gemfiles/multi_xml.gemfile'
          - ruby: 2.7
            gemfile: 'gemfiles/rails_7.gemfile'
    runs-on: ubuntu-20.04
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      COVERALLS_PARALLEL: true

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake spec

    - name: Run tests (spec/integration/eager_load)
      if: ${{ matrix.gemfile == 'Gemfile' }}
      run: bundle exec rspec spec/integration/eager_load

    - name: Run tests (spec/integration/multi_json)
      if: ${{ matrix.gemfile == 'gemfiles/multi_json.gemfile' }}
      run: bundle exec rspec spec/integration/multi_json

    - name: Run tests (spec/integration/multi_xml)
      if: ${{ matrix.gemfile == 'gemfiles/multi_xml.gemfile' }}
      run: bundle exec rspec spec/integration/multi_xml
